### ISSUE TITLE
Can't change font color of "Scenes" "Drafts" and "Compile" tabs

### ISSUE THREAD

**Issue by ahwalton** [kevboh/longform#68] opened 2022-06-02 14:27 UTC
![longform example](https://user-images.githubusercontent.com/69476861/171652360-5c784f43-68f9-4c12-8f12-650f59b47fcd.PNG)
![longform example 2](https://user-images.githubusercontent.com/69476861/171652379-b9025cd5-dc53-46fc-92dd-3497292ce1d8.PNG)

I'm using Minimal Theme with Style Settings and experiencing a problem with font colors in Longform. I've changed my link color to the green you can see above, but it only effects the front color active tab. The inactive tabs remain the default blue color for links. I've combed through the options for Minimal Theme, Style Settings and Longform and tried everything that seems relevant, but I can't find anything that changes the color of the font on these inactive tabs. 

Minimal Theme V5.2.8
Using color scheme "Things" in Dark Mode

Style Settings v0.4.10

Longform v1.1.0

Please let me know if this is an issue I should be posting for Style Settings instead. I'm posting it here because the only place this problem occurs is in the Longform pane with these specific tabs shown in the screenshot. 

Thanks,

**Comment by kevboh** [comment] 2022-06-20 14:49
Interesting—I'll have to look at those components. Have you tried turning developer mode on and Inspecting those links to see what their classes are?

In general Longform doesn't always play nice with themes—I just haven't had the time to make it do so, and don't use themes personally so it's not a thing I'm forced to fix. But I should do so.

**Comment by kevboh** [comment] 2022-08-13 12:11
I can't reproduce this in the 2.0 beta w/ Minimal and Style Settings. 2.0 should reach production fairly soon. Closing this, please reopen if you still see it.

**Closed by kevboh** 2022-08-13 12:11 UTC
Labels: bug, good first issue, projects
