### ISSUE TITLE
No scrollbars

### ISSUE THREAD

**Issue by chrismelbourne** [kevboh/longform#61] opened 2022-04-24 01:07 UTC
All the longform pages (preview or editing mode) have no scrollbars, which is inconvenient with long chapters.

Is this a feature or a bug? 

If an intended feature, it would be great to add an option to the plugin so we have the choice to toggle it off?

Otherwise, great plugin, works as intended! Thank you!

**Comment by kevboh** [comment] 2022-08-10 13:07
I can't reproduce this. You're saying the note panes don't have scrollbars? Longform doesn't apply any styling to those panes, only an additional class for you to add your own CSS. Are you using a custom theme or CSS snippet?

**Comment by kevboh** [comment] 2024-01-20 00:56
Closing; let me know if this is still happening. Longform doesn't touch scrollbars, so I suspect this was a theme issue.

**Closed by kevboh** 2024-01-20 00:56 UTC
Labels: needs investigating
