### ISSUE TITLE
Feature Request: Ability to move a set of nested scenes as a group to another scene

### ISSUE THREAD

**Issue by etobias-musiced** [kevboh/longform#211] opened 2023-11-01 18:21 UTC
**Describe the solution you'd like**
This might already be possible - I am trying to take a set of nested scenes (files) and move it from being nested under one scene to be nested under a different scene since I'm structuring this writing project as I go. Ideally, I would like to be able to drag a top level scene (with the nested scenes/files under it) of a group of files to a new scene or place in the longform window and have all the nested scenes/files follow it. When I currently drag a top level scene it doesn't carry any of the nested scenes with it and I have to manually drag each one to the new place in the scene window.

**Describe alternatives you've considered**

I tried folding all of the nested scenes and dragging the top level scene but that still left all the nested scenes in the same place and I had to manually drag them.

I tried selecting multiple scenes and dragging them as a group but that did not work either. 

Thank you!

**Comment by b-camphart** [comment] 2023-11-01 20:25
Probably a duplicate of #161

**Comment by etobias-musiced** [comment] 2023-11-01 22:05
oh yes #161 has that nice visual as well - thank you! didn't see this earlier

**Closed** 2023-11-13 18:39 UTC
Labels: enhancement
