### ISSUE TITLE
Bug: The progress bar doesn't go up

### ISSUE THREAD

**Issue by SylferDD** [kevboh/longform#156] opened 2023-04-10 15:03 UTC
**Versions**
Longform version: 2.0.3
Obsidian version: v1.1.16
OS [e.g. macOS, Windows, iOS, Android]:  Windows 10
Theme:
Other plugins that you think might be relevant here:

Hello,
I just installed the plugin. I was looking for an alternative to Scrivener, and the progress bar is a tool that really enticed me.
The problem : the progress bar doesn't work. When I type words in the longform project, the progress bar doesn't go up.
And when I reach the daily goal, no pop up appears.

Thank you in advance.

Here are screenshots to show my problem : 
![ProgressBarProblem](https://user-images.githubusercontent.com/86682169/230928184-c169c2d2-7b5b-4018-aa56-4a3b447a94e9.jpg)
![ProgressBarProblem2](https://user-images.githubusercontent.com/86682169/230928203-b2db5bca-ac86-483c-b17e-236d1c036807.jpg)

**Comment by astoicstradingtools** [comment] 2023-07-09 09:26
I'm encountering the same bug

**Comment by neilgoodman** [comment] 2023-07-20 16:47
This may be a dupe of #93

**Comment by kevboh** [comment] 2023-07-20 16:52
Closing for now as fixed, if encountered again can reopen.

**Closed by kevboh** 2023-07-20 16:52 UTC
Labels: bug, projects
