### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by gernalix** [kevboh/longform#17] opened 2021-08-11 19:31 UTC
Whatever I click on scenes, drafts, compile, nothing happens.
![X4GnrevRLF](https://user-images.githubusercontent.com/22417984/129091279-51b4f4f3-4902-49ba-a7dd-70ead6c1dcbf.gif)

**Comment by gernalix** [comment] 2021-08-11 19:34
[Index.md](https://github.com/kevboh/longform/files/6970928/Index.md)
I'm using v 1.0.3

**Comment by kevboh** [comment] 2021-08-11 20:03
@gernalix in the meantime, try:

1. Unmarking the project (or clicking the reset button in Longform settings)
2. Restarting Obsidian.
3. Deleting the Index file.
4. Marking the project again.

**Comment by kevboh** [comment] 2021-08-11 20:06
Alternatively, you can replace the frontmatter in Index.md with

```
---
version: 1
drafts:
  - name: Draft 1
    folder: Draft 1
    scenes: []
---
```

Assuming the folder in your project is named `Draft 1`.

**Comment by gernalix** [comment] 2021-08-11 20:08
> @gernalix in the meantime, try:
> 
> 1. Unmarking the project (or clicking the reset button in Longform settings)
> 2. Restarting Obsidian.
> 3. Deleting the Index file.
> 4. Marking the project again.

it works now. But shouldn't the bullet points be aligned with the scene titles? 
![image](https://user-images.githubusercontent.com/22417984/129096122-f3e7f84c-8228-43c6-adaf-651b6af3201f.png)

**Comment by Moonbase59** [comment] 2021-08-11 21:24
@gernalix Ha. Seems you _renamed_ your Longform folder _after_ making it one? (This will break the index because suddenly everything is "undefined").

@kevboh Any chance you could try to catch that by using one of the Obsidian API events?

This error confuses Longform very much—it can’ acces other Longform projects anymore in the Longform pane after such an incident.

Fortunately, it picks up correctly after doing a general "Untrack" in settings. Old Index files are correctly re-read.

**Comment by kevboh** [comment] 2021-08-12 14:02
Renaming is supposed to be covered, but it's likely that there's some bug there causing this.

**Comment by kevboh** [comment] 2021-08-13 00:25
I'm going to close this as I'm not sure what can cause it, if you're able to reliably reproduce it please open and list those steps.

**Closed by kevboh** 2021-08-13 00:25 UTC
