### ISSUE TITLE
Bug: Drafts not generating

### ISSUE THREAD

**Issue by sfield541** [kevboh/longform#199] opened 2023-09-27 00:27 UTC
**Versions**
Longform version:
Obsidian version:
OS [e.g. macOS, Windows, iOS, Android]: 
Theme:
Other plugins that you think might be relevant here:

**Describe the bug**
When generating drafts, the index file is not duplicated for the draft. Only the current date appears in the frontmatter.

**To Reproduce**
1. Go to 'Create new draft'
2. Click on '+'
4. Scroll down to 'add scense'
5. Click on 'create draft'
6. See error: Draft briefly appears in the project then disappears

**Expected behavior**
New draft name should appear in the draft list but it doesn't

**Screenshots**

**Additional context**
I try restarting Obsidian but no change.

**Comment by kevboh** [comment] 2023-09-28 15:30
I can't reproduce this. It also sounds like maybe you're using an old version of Longform? Can you please share Longform + Obsidian version plus the other data in the issue template? Thank you.

**Comment by kevboh** [comment] 2024-01-28 14:26
Still can't repro, closing.

**Closed by kevboh** 2024-01-28 14:26 UTC
Labels: needs investigating
