### ISSUE TITLE
 Folding doesn't work right in Minimal Theme

### ISSUE THREAD

**Issue by squareyed** [kevboh/longform#198] opened 2023-09-25 02:18 UTC
See: https://github.com/kepano/obsidian-minimal/issues/627 

When a scene with sub-scenes is folded, the rows for the sub-scenes remain visible but blank.  They don't fold away. You can still click on them blindly and drag them off to other places. 

This works properly in all other themes I've tried, so maybe it's purely a Minimal problem? In any case, you might want to check that out.

Thanks in advance!

**Comment by b-camphart** [comment] 2023-09-25 05:11
Seems like a duplicate of #138 which was just closed.  It's an issue with minimal theme, but you can fix it with a CSS snippet.  Once a new build comes out with the updated CSS classes introduced in #186, creating that snippet should be pretty easy.

**Comment by kevboh** [comment] 2023-09-28 15:27
Right, if this doesn't occur in base or other themes it feels like the fix should be on the Minimal side, but ideally a snippet will also service. I won't be able to cut a new build until next week.

**Closed by kevboh** 2023-09-28 15:27 UTC
Labels: bug

**Comment by squareyed** [comment] 2024-01-22 21:47
This is working now for me with Minimal 7.4.7 and Longform 2.0.4
