### ISSUE TITLE
Bug: can't load my longform project after restart my obsidian

### ISSUE THREAD

**Issue by luojiang-killgrave** [kevboh/longform#229] opened 2024-01-08 02:12 UTC
**Versions**
Longform version: 2.0.4
Obsidian version: 1.5.3
OS [e.g. macOS, Windows, iOS, Android]:  windows and macOS
Theme: default
Other plugins that you think might be relevant here: I disabled all other plugins( `Better Word Count`,`Dataview`,`Excalidraw`,`Importer`, `Timelines` ), nothing changed.

**Describe the bug**
well, after I create a longform project, it works fine. but after I put my laptop away for a while(maybe over a night), when I reopen my obsidian, my longform project just can't show anything, I tried to press the button beside `Drafts`, It shows like this (with console log, hope it helps)
<img width="1164" alt="image" src="https://github.com/kevboh/longform/assets/36988985/14d4810a-9199-47b4-81c7-76e8118b5c58">

**To Reproduce**
1. don't really know, just leave my latop for a while

**Expected behavior**

**Screenshots**
<img width="273" alt="image" src="https://github.com/kevboh/longform/assets/36988985/73ae5f36-d3c8-45a9-baf8-0607c42666d7">

**Additional context**
I am using Google Drive to store all my files, share between my windows laptop(surface laptop3) and a macbook pro. but this bug happened during I operate on my windows laptop.

**Comment by luojiang-killgrave** [comment] 2024-01-08 02:17
I tried to create a new longform project then delete it, my old longform project came back! (with scenes disordered)
hope this helpful

**Comment by jgharding** [comment] 2024-01-08 15:26
In case it helps, I’ve had this pop up and the issue is usually resolved by closing and reopening Obsidian.

**Comment by kevboh** [comment] 2024-01-19 21:30
This almost always happens because the yaml in the index file is malformed in some way. This is easiest to diagnose by opening the yaml in a text editor like VSCode and looking at it.

**Closed by kevboh** 2024-01-19 21:30 UTC
Labels: bug
